#include "pch.h"
#include "../Public/AdminActions.h"
#include "../../FortniteGame/Public/BattleRoyaleGamePhaseLogic.h"
#include "../../FortniteGame/Public/BuildingSMActor.h"
#include "../../FortniteGame/Public/FortInventory.h"
#include "../../FortniteGame/Public/FortPlaylistAthena.h"
#include "../../FortniteGame/Public/FortSafeZoneIndicator.h"
#include "../Public/Utils.h"
#include <fstream>
#include <sstream>

void AdminActions::StartBusEarly()
{
    if (UFortGameStateComponent_BattleRoyaleGamePhaseLogic::GetDefaultObj())
        UFortGameStateComponent_BattleRoyaleGamePhaseLogic::bStartAircraft = true;
    else
        UKismetSystemLibrary::ExecuteConsoleCommand(UWorld::GetWorld(), FString(L"startaircraft"), nullptr);
}

void AdminActions::PauseSafeZone()
{
    UFortGameStateComponent_BattleRoyaleGamePhaseLogic::bPausedZone = true;

    auto GameMode = (AFortGameMode*)UWorld::GetWorld()->AuthorityGameMode;
    if (GameMode->HasbSafeZonePaused())
        GameMode->bSafeZonePaused = true;

    UKismetSystemLibrary::ExecuteConsoleCommand(UWorld::GetWorld(), FString(L"pausesafezone"), nullptr);
}

void AdminActions::ResumeSafeZone()
{
    UFortGameStateComponent_BattleRoyaleGamePhaseLogic::bPausedZone = false;

    auto GameMode = (AFortGameMode*)UWorld::GetWorld()->AuthorityGameMode;
    if (GameMode->HasbSafeZonePaused())
        GameMode->bSafeZonePaused = false;

    UKismetSystemLibrary::ExecuteConsoleCommand(UWorld::GetWorld(), FString(L"startsafezone"), nullptr);
}

static AFortSafeZoneIndicator* GetSafeZoneIndicator()
{
    auto GameMode = (AFortGameMode*)UWorld::GetWorld()->AuthorityGameMode;
    if (GameMode->HasSafeZoneIndicator())
        return GameMode->SafeZoneIndicator;

    auto GamePhaseLogic = UFortGameStateComponent_BattleRoyaleGamePhaseLogic::Get(UWorld::GetWorld());
    return GamePhaseLogic ? GamePhaseLogic->SafeZoneIndicator : nullptr;
}

void AdminActions::SkipSafeZone()
{
    if (auto Indicator = GetSafeZoneIndicator())
    {
        Indicator->SafeZoneStartShrinkTime = (float)UGameplayStatics::GetTimeSeconds(UWorld::GetWorld());
        Indicator->SafeZoneFinishShrinkTime = Indicator->SafeZoneStartShrinkTime + 0.05f;
    }
}

void AdminActions::StartShrinkingSafeZone()
{
    if (auto Indicator = GetSafeZoneIndicator())
        Indicator->SafeZoneStartShrinkTime = (float)UGameplayStatics::GetTimeSeconds(UWorld::GetWorld());
}

void AdminActions::ResetBuilds()
{
    TArray<ABuildingSMActor*> Builds;
    Utils::GetAll<ABuildingSMActor>(Builds);

    for (auto& Build : Builds)
        if (Build->bPlayerPlaced)
            Build->K2_DestroyActor();

    Builds.Free();
}

void AdminActions::DestroyFloorLoot()
{
    TArray<AFortPickupAthena*> Pickups;
    Utils::GetAll<AFortPickupAthena>(Pickups);

    for (auto& Pickup : Pickups)
        Pickup->K2_DestroyActor();

    Pickups.Free();
}

static void WriteDumpHeader(std::stringstream& ss)
{
    ss << "Generated by Erbium (https://github.com/plooshi/Erbium)\n";
    char version[6];
    sprintf_s(version, VersionInfo.FortniteVersion >= 5.00 || VersionInfo.FortniteVersion < 1.2 ? "%.2f" : "%.1f", VersionInfo.FortniteVersion);
    ss << "Fortnite version: " << version << "\n\n";
}

static void DumpRarity(std::stringstream& ss, int Rarity)
{
    auto Names = *(TArray<TPair<FName, int64>>*)(__int64(EFortRarity::StaticEnum()) + 0x40);

    for (int i = 0; i < Names.Num(); i++)
    {
        auto& Pair = Names[i];
        auto& Name = Pair.Key();
        auto& Value = Pair.Value();

        if (Value == Rarity)
        {
            auto str = Name.ToString();
            auto pos = str.rfind("::");

            auto RealName = pos == std::string::npos ? str : str.substr(pos + 1);
            ss << "-     Rarity: " << RealName << "\n";
        }
    }
}

void AdminActions::DumpItems()
{
    std::stringstream ss;
    WriteDumpHeader(ss);

    for (int i = 0; i < TUObjectArray::Num(); i++)
    {
        auto Object = TUObjectArray::GetObjectByIndex(i);
        if (!Object || !Object->Class || Object->IsDefaultObject() || !Object->IsA<UFortWorldItemDefinition>())
            continue;
        auto Item = (UFortWorldItemDefinition*)Object;

        FString Name = UKismetTextLibrary::Conv_TextToString(Item->HasDisplayName() ? Item->DisplayName : Item->ItemName);

        ss << "- " << UKismetSystemLibrary::GetPathName(Item).ToString() << "\n";
        ss << "-     Name: " << (Name.GetData() ? Name.ToString() : "None") << "\n";

        DumpRarity(ss, Item->Rarity);
    }

    std::ofstream of("DumpedItems.txt", std::ios::trunc);
    of << ss.str();
}

void AdminActions::DumpPlaylists()
{
    std::stringstream ss;
    WriteDumpHeader(ss);

    for (int i = 0; i < TUObjectArray::Num(); i++)
    {
        auto Object = TUObjectArray::GetObjectByIndex(i);
        if (!Object || !Object->Class || Object->IsDefaultObject() || !Object->IsA<UFortPlaylistAthena>())
            continue;
        auto Playlist = (UFortPlaylistAthena*)Object;

        FString Name = UKismetTextLibrary::Conv_TextToString(Playlist->UIDisplayName);

        ss << "- " << UKismetSystemLibrary::GetPathName(Playlist).ToString() << "\n";
        ss << "-     Name: " << (Name.GetData() ? Name.ToString() : "None") << "\n";
        if (Playlist->HasMaxPlayers())
            ss << "-     Max players: " << std::to_string(Playlist->MaxPlayers) << "\n";
        if (Playlist->HasMaxSquadSize())
            ss << "-     Squad size: " << std::to_string(Playlist->MaxSquadSize) << "\n";
    }

    std::ofstream of("DumpedPlaylists.txt", std::ios::trunc);
    of << ss.str();
}
